import React from "react";  
import Plan from "./Plan";

export const metadata = {
  title: "FitLog | My Plan",
  description: "Generated by Fuad",
};


const MyPlan = () => {
  return (
   <>
   <Plan/>
   </>
  );
}

export default MyPlan;
